### PR TITLE
fix: teleport call that doesn't check world

### LINKED ISSUE #506: fix: add an error message if the world doesnt exist for an existing destination
Atm it just outputs an error log.

### PR DESCRIPTION
**Pull request by TreemanKing**
fixes #506

### CODE REVIEW

File: core/src/main/java/com/sekwah/advancedportals/core/tags/DestiTag.java [hunk 1]
```diff
@@ -134,6 +142,14 @@ public boolean activated(TagTarget target, PlayerContainer player,
         var selectedArg = activationData.getMetadata(TAG_NAME);
         Destination destination =
             destinationServices.getDestination(selectedArg);
+
+        if (serverContainer.getWorld(destination.getLoc().getWorldName()) == null) {
+            infoLogger.warning(Lang.translateInsertVariables(
```
Comment (sekwah41) [inline core/src/main/java/com/sekwah/advancedportals/core/tags/DestiTag.java:147]: You want to be telling the player the issue not the console logs so that admins without console access can see it when they test the portals they make.

**Review by sekwah41 — CHANGES_REQUESTED** [review]

File: core/src/main/java/com/sekwah/advancedportals/core/tags/DestiTag.java (hunk 1 above)
Comment (TreemanKing) [reply core/src/main/java/com/sekwah/advancedportals/core/tags/DestiTag.java:147]: This isn't on creation though, this is when it is activated meaning that sending it to admins/players is pointless. A better way is stating the `destination.name` has an invalid world rather. This goes into also considering players can change the configuration and such offline and there is no checks to verify the world is actually loaded or not.

**Review by sekwah41 — APPROVED** [review]
