### PR TITLE
fix: trigger block validation

### LINKED ISSUE #504: Make sure materials are checked on creation
It's possible to make portals with materials that don't exist, spelt wrong or have wrong caps.

### PR DESCRIPTION
**Pull request by TreemanKing**
Fixes #504

### CODE REVIEW

File: core/src/main/java/com/sekwah/advancedportals/core/tags/TriggerBlockTag.java [hunk 1]
```diff
@@ -48,4 +55,29 @@ public List<String> autoComplete(String argData) {
 
         return triggerBlocks;
     }
+
+    @Override
+    public boolean created(TagTarget target, PlayerContainer player, String[] argData) {
+        for (int i = 0; i < argData.length; i++) {
+            String material = argData[i].toUpperCase(Locale.ROOT);
```
Comment (sekwah41) [inline core/src/main/java/com/sekwah/advancedportals/core/tags/TriggerBlockTag.java:62]: dont automatically convert to uppercase, one issue is that when we add the forge versions their materials are in lower case. Preferably, add a method to the server container to try to match the material and return the matched name. That way we can make it per implementation based.

File: core/src/main/java/com/sekwah/advancedportals/core/tags/TriggerBlockTag.java [hunk 2]
```diff
@@ -48,4 +55,29 @@ public List<String> autoComplete(String argData) {
...
+        return true;
+    }
+
+    @Override
+    public void destroyed(TagTarget target, PlayerContainer player, String[] argData) {
+
+    }
+
+    private boolean isValidMaterial(String material) {
+        // Assuming serverContainer has a method to get all valid materials
```
Comment (sekwah41) [inline core/src/main/java/com/sekwah/advancedportals/core/tags/TriggerBlockTag.java:78]: Comment not needed as the fact its part of the implementation interface assumes it would be implemented.

**Review by sekwah41 — CHANGES_REQUESTED** [review]

File: core/src/main/java/com/sekwah/advancedportals/core/tags/TriggerBlockTag.java [hunk 3]
```diff
@@ -38,14 +44,38 @@ public String description() {
...
         return triggerBlocks;
     }
-}
+
+    @Override
+    public boolean created(TagTarget target, PlayerContainer player, String[] argData) {
+        for (int i = 0; i < argData.length; i++) {
+            String material = serverContainer.matchMaterialName(argData[i]);
+            if (material == null || !isValidMaterial(material)) {
+                infoLogger.warning(Lang.translate("tag.triggerblock.error.invalidmaterial"));
```
Comment (sekwah41) [inline core/src/main/java/com/sekwah/advancedportals/core/tags/TriggerBlockTag.java:63]: Don't you want to tell the player what they got wrong rather than just logging it in the console?

**Review by sekwah41 — CHANGES_REQUESTED** [review]

**Review by sekwah41 — APPROVED** [review]
