### PR TITLE
fix: comment out log spam

### LINKED ISSUE #495: bug: log feedback spam
When creating a portal and putting a destination that doesn't exist, it will spam log even though the command hasn't been outputted. For e.g. 

image

Reproduce steps:
1. /aportals create name:test desti:test1234567890 
2. it will show the above screenshot

It is best that we leave it until after the command is processed.

### PR DESCRIPTION
**Pull request by TreemanKing**
Fixes #495

### CODE REVIEW

File: spigot/src/main/java/com/sekwah/advancedportals/spigot/AdvancedPortalsPlugin.java [hunk 1]
```diff
@@ -88,8 +88,6 @@ public void onEnable() {
 
         this.portalsCore.registerPortalCommand("import",
                                                new ImportPortalSubCommand());
-
-        new Metrics(this);
```
Comment (sekwah41) [inline spigot/src/main/java/com/sekwah/advancedportals/spigot/AdvancedPortalsPlugin.java:92]: Why is this being removed?

Comment (sekwah41) [reply spigot/src/main/java/com/sekwah/advancedportals/spigot/AdvancedPortalsPlugin.java:92]: Ah a dupe xD

**Review by sekwah41 — APPROVED** [review]
Need to check why this is logging anyway but will approve for now to fix the immediate spammy logs
